# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
    release:
        types: [created]
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: yarn ci

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - run: yarn ci
            - name: Check Commit Messages
              id: commit_check
              run: |
                  commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
                  if [[ "${{ github.event_name }}" == 'push' && $commit_message =~ '^(docs:|chore:)' ]]; then
                    echo "Skipping npm publish due to commit message."
                    echo "skip_publish=true" >> $GITHUB_ENV
                  else
                    echo "skip_publish=false" >> $GITHUB_ENV
                  fi

            - run: |
                  if [[ "${{ env.skip_publish }}" == 'true' ]]; then
                    echo "Skipping npm publish due to commit message."
                  else
                    npm publish --access public
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
